server:
  #  port: ${random.int[1024,9999]}
  port: 9090
logging:
  level:
    com.geblob.cloud.controller: debug
spring:
  rabbitmq:
    password: admin
    port: 5672
    host: vision
    username: admin