server:
  #  port: ${random.int[1024,9999]}
  port: 8761
logging:
  level:
    com.geblob.cloud.controller: debug
spring:
  rabbitmq:
    password: admin
    port: 5672
    host: 127.0.0.1
    username: admin
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false